### ISSUE TITLE
Layout overflow in small screens

### ISSUE THREAD

**Issue by andre-paraense** [nemoryoliver/rating_dialog#1]
The `RatingDialog` widget is presenting an overflow in small screens. For instance, in screens of size 480x 800, we get a right overflow of 40 pixels in the stars icons, as shown below:

<img width="391" alt="Screenshot 2019-06-29 at 18 45 13" src="https://user-images.githubusercontent.com/4104595/60387666-7205be00-9a9e-11e9-80a5-5c307653d359.png">

**Comment by nemoryoliver** [comment]
Version 2.0.0 is now published with a new rating bar and overflow fixes for smaller screens. Thank you
