### ISSUE TITLE
Migrating onSubmitPressed to onSubmitted

### ISSUE THREAD

**Issue by zakblacki** [nemoryoliver/rating_dialog#13]
I'm getting error when I migrated to onSubmitted

> The argument type 'Null Function(int)' can't be assigned to the parameter type 'dynamic Function(RatingDialogResponse)'.

```
       onSubmitted: (int rating) {
            print("onSubmitPressed: rating = $rating");
            AppReview.writeReview;
          },
    initState() {
    AppReview.getAppID.then((onValue) {
      setState(() {
        appID = onValue;
      });
      print("App ID" + appID);
    });
   }
```

**Comment by nemoryoliver** [comment]
> RatingDialogResponse

Please use the new template from: [Example](https://github.com/nemoryoliver/rating_dialog/blob/master/example/lib/example.screen.dart)

Replace your onSubmitted block to 

```
onSubmitted: (response) {
        print("onSubmitPressed: rating =  ${response.rating},");
        AppReview.writeReview;
},
```

**Comment by zakblacki** [comment]
Thanks 
how about this 

`image: const FlutterLogo(size: 100, colors: Colors.blue),`
          
it does not recognize colors

**Comment by nemoryoliver** [comment]
> Thanks
> how about this
> 
> `image: const FlutterLogo(size: 100, colors: Colors.blue),`
> 
> it does not recognize colors

It appears FlutterLogo doesn't have a **color** property [FlutterLogo Docs](https://api.flutter.dev/flutter/material/FlutterLogo-class.html). Also, please use your IDE's autocomplete feature to get suggestions on what properties the object supports.
