### ISSUE TITLE
Hide comment hint after the field is focused

### ISSUE THREAD

**Issue by fotiDim** [nemoryoliver/rating_dialog#19]
The UI is a bit confusing now as after tapping the comment field the hint is still displayed with a fairly visible color. I was literally hitting backspace trying to erase the hint text in order to write my comment. 

I would rather:
- hide the hint when the field is in focus or
- make the color more transparent so that it clearly indicates that it will go away when you start typing.

**Comment by oliverbytes** [comment]
An option to hide it when focused is possible. However, I like to follow the standard UX for flutter which is the current default behavior. You could however fork this repo to add that functionality. Thank you for your suggestion though. 

Closing this issue.
