### ISSUE TITLE
Add option to reduce star size 

### ISSUE THREAD

**Issue by zakblacki** [nemoryoliver/rating_dialog#22]
On small screen the stars size takes two row 
please add option to control the star size thanks

**Comment by oliverbytes** [comment]
A new `starSize` parameter is added in the latest version! Thank you for your suggestion

**Comment by zakblacki** [comment]
![image](https://user-images.githubusercontent.com/29728429/139586211-7049fb7a-54e6-4026-b870-df21cdb47761.png)
We also need option to center the text title 
and 'message' parameters should be optional
