### ISSUE TITLE
Error: Getter not found: 'context'.     context: context,

### ISSUE THREAD

**Issue by areeba-farooq** [nemoryoliver/rating_dialog#25]
void showRatingDialog() {
  final ratingDialog = RatingDialog(
    ratingColor: Colors.amber,
    title: 'Rate this app',
    message: "If you enjoy using this app, would you mind taking a moment to rate it? Thank you, for your support!",
    submitButton: 'Submit',
    onCancelled: () => print('cancelled'),
    onSubmitted: (response) {
      print('rating: ${response.rating}, ');
      print('comment: ${response.comment}');
    },
  );

  showDialog(
    context: context,             //this line giving error.
    barrierDismissible: true,
    builder: (context) => ratingDialog,

  );

**Comment by oliverbytes** [comment]
Please be specific on your issue, also showing the full log will be helpful. Open a new issue if you're still experiencing this. Thank you
