### ISSUE TITLE
Please add initialValue prop

### ISSUE THREAD

**Issue by topex-psy** [nemoryoliver/rating_dialog#3]
I need to set the initial value of the rating, for example when user go back to the dialog in order update their rating, the stars show up with the initial value of their former rating. Thank you.

**Comment by davidAg9** [comment]
you can set that from your code 
and then you can get the value from onsubmitted function and set your variable as you please

**Comment by nemoryoliver** [comment]
Version 2.0.0 is now published with a way to set initial rating value.
